### PR TITLE
Update liblogicalaccess.config

### PR DESCRIPTION
**Pull request by maxim-smirnov**
Fixed plugins folder

### CODE REVIEW

**Comment by Liryna** [comment]
Hello @maxim-smirnov ,

`/usr/lib/logicalaccess` is the corrent plugin folder. It is where the debian package install them.
https://github.com/islog/liblogicalaccess-debian/blob/master/debian/liblogicalaccess-dev.dirs#L2

I guess you propose this PR because your plugins are installed in /usr/lib with cmake install ?

**Comment by maxim-smirnov** [comment]
Yes, I thought that it's problem for all packages. Maybe create additional config for installation with cmake?

**Comment by Liryna** [comment]
Humm or probably we should just add the folder /usr/lib to the PluginFolders.
For now only debian use the `/usr/lib/logicalaccess`

**Comment by maxim-smirnov** [comment]
Yeah, I think, that it's good idea. I'll open new pull request.

**Pull request closed without merging**
